---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
  - name: bosh-src
  - name: stemcell
  - name: bosh-release

run:
  path: bosh-src/ci/tasks/test-bbr.sh

params:
  FOCUS_SPEC: ""
  RDS_MYSQL_EXTERNAL_DB_HOST: replace-me
  RDS_MYSQL_EXTERNAL_DB_USER: replace-me
  RDS_MYSQL_EXTERNAL_DB_PASSWORD: replace-me
  RDS_MYSQL_EXTERNAL_DB_NAME: replace-me
  RDS_POSTGRES_EXTERNAL_DB_HOST: replace-me
  RDS_POSTGRES_EXTERNAL_DB_USER: replace-me
  RDS_POSTGRES_EXTERNAL_DB_PASSWORD: replace-me
  RDS_POSTGRES_EXTERNAL_DB_NAME: replace-me
  GCP_MYSQL_EXTERNAL_DB_HOST: replace-me
  GCP_MYSQL_EXTERNAL_DB_USER: replace-me
  GCP_MYSQL_EXTERNAL_DB_PASSWORD: replace-me
  GCP_MYSQL_EXTERNAL_DB_NAME: replace-me
  GCP_MYSQL_EXTERNAL_DB_CLIENT_CERTIFICATE: replace-me
  GCP_MYSQL_EXTERNAL_DB_CLIENT_PRIVATE_KEY: replace-me
  GCP_POSTGRES_EXTERNAL_DB_HOST: replace-me
  GCP_POSTGRES_EXTERNAL_DB_USER: replace-me
  GCP_POSTGRES_EXTERNAL_DB_PASSWORD: replace-me
  GCP_POSTGRES_EXTERNAL_DB_NAME: replace-me
  GCP_POSTGRES_EXTERNAL_DB_CLIENT_CERTIFICATE: replace-me
  GCP_POSTGRES_EXTERNAL_DB_CLIENT_PRIVATE_KEY: replace-me
  STEMCELL_OS: ""
