---
groups:
  - name: bosh
    jobs:
      - brats-ubuntu-trusty
      # - brats-ubuntu-xenial

jobs:
  - name: brats-ubuntu-trusty
    serial: true
    plan:
    - do:
      - aggregate:
        - get: bosh-src
        - get: bosh-dns-release
        - get: stemcell
          resource: warden-ubuntu-trusty
        - get: bosh-release
          resource: bosh-candidate-release-tarballs
          trigger: true
      - task: test-brats
        file: bosh-src/ci/tasks/test-brats.yml
        tags: ["worker-brats"]
        privileged: true
        params:
          FOCUS_SPEC: "BoshDns"
          STEMCELL_OS: ubuntu-trusty

  # - name: brats-ubuntu-xenial
  #   serial: true
  #   plan:
  #   - do:
  #     - aggregate:
  #       - get: bosh-src
  #       - get: bosh-dns-release
  #       - get: stemcell
  #         resource: warden-ubuntu-xenial
  #       - get: bosh-release
  #         resource: bosh-candidate-release-tarballs
  #         trigger: true
  #     - put: brats-mutex
  #       params: {acquire: true}
  #     - task: test-brats
  #       file: bosh-src/ci/tasks/test-brats.yml
  #       tags: ["worker-brats"]
  #       privileged: true
  #       params:
  #         FOCUS_SPEC: "BoshDns"
  #         STEMCELL_OS: ubuntu-xenial

resources:
  - name: bosh-src
    type: git
    source:
      uri: ((bosh_src_url))
      branch: wip-faster-brats
      private_key: ((github_deployment_key))

  - name: bosh-candidate-release-tarballs
    type: s3
    source:
      bucket: ((candidate_release_bucket))
      access_key_id: ((candidate_release_access_key_id))
      secret_access_key: ((candidate_release_secret_access_key))
      versioned_file: "bosh-dev-release.tgz"


  - name: bosh-dns-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh-dns-release

  #
  # BATS
  #


  - name: warden-ubuntu-trusty
    type: bosh-io-stemcell
    source:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent

  # - name: warden-ubuntu-xenial
  #   type: bosh-io-stemcell
  #   source:
  #     name: bosh-warden-boshlite-ubuntu-xenial-go_agent

